### ISSUE TITLE
Game crashes when trying to launch 1.12.0.2

### ISSUE THREAD

**Issue by ZebulanStanphill** [minecraft-linux/mcpelauncher-ui-manifest#10]
The launcher is working for me with 1.11.0.10, but when I try to launch 1.12.0.2, it crashes and I get this error log:

https://pastebin.com/398kzgS5

I am using Antergos Linux and the following AUR packages:

- `mcpelauncher-linux-git` v0.1.beta.2.r26.g413bbbb-1
- `mcpelauncher-msa-git` v0.1.beta.2.r0.g4a0ccb0-1
- `mcpelauncher-msa-ui-qt-git` v0.1.beta.2.r0.g4a0ccb0-1
- `mcpelauncher-ui-git` v0.1.beta.1.r8.g92d286a-1

**Comment by MCMrARM** [comment]
Aware, will fix later today.

**Comment by ZebulanStanphill** [comment]
After rebuilding the AUR packages to the latest versions, 1.12.0.2 launches without a problem!
