### ISSUE TITLE
Cannot sign in with google: This browser or app may not be secure

### ISSUE THREAD

**Issue by rocka** [minecraft-linux/mcpelauncher-ui-manifest#12]
Just download the launcher AppImage, when I try to sign in, this happens ...

![image](https://user-images.githubusercontent.com/13914967/71396472-416d9e00-2655-11ea-99ee-0bc8fe9cdd98.png)

Google appears to be denying users access based on the browser, see 
https://www.omgubuntu.co.uk/2019/12/couldnt-sign-you-in-google-browser-error-linux

And according to the comments under that post, change the UserAgent might help.

**Comment by andy-mortimer** [comment]
I see the same. Just installed the latest version, on MacOS, and got stuck at this point.

**Comment by andy-mortimer** [comment]
Is this the same issue as https://github.com/minecraft-linux/mcpelauncher-ui-qt/issues/6 , now fixed? It looks like it.

**Comment by rocka** [comment]
Oh, I tried build them from source, it appears as a samsung phone, and login just fine. I'll close this.

**Comment by andy-mortimer** [comment]
Nice, thanks for following up. I'm currently struggling to get the build from source to work but good to know I'm on the right track!

**Comment by andy-mortimer** [comment]
@MCMrARM does the MacOS prebuilt binary at https://mrarm.io/r/mcpelauncher-osx include this fix? I couldn't find a Help>About with a version number to check it but I'm assuming not because it gives this symptom. I am trying to build from source but it seems recent XCodes don't like 32-bit builds or something; a pre-built version with this fix would be very convenient! :)

**Comment by andy-mortimer** [comment]
One last comment from me, in case other people are in the same situation and find this thread: the reason I couldn't build from source on MacOS was that I've upgraded to Catalina, and so the required 32-bit parts of MCPELauncher will neither build nor run: https://mcpelauncher.readthedocs.io/en/latest/troubleshooting.html#macos-x-catalina-could-not-find-the-game-launcher So updating the MacOS prebuilt binary is probably fairly futile now

**Comment by parkerlreed** [comment]
Guess who's back... 

![image](https://user-images.githubusercontent.com/841440/184208934-31c4947b-84bc-4d71-88ab-95af73fecb13.png)
