### ISSUE TITLE
Does not list nether update

### ISSUE THREAD

**Issue by sijohans** [minecraft-linux/mcpelauncher-ui-manifest#21]
I cannot see the nether update in the list when using the mcpelauncher-ui-qt. I can only see the latest beta (1.16.0.68). Any ideas?

**Comment by ChristopherHX** [comment]
> I can only see the latest beta

You should either opt out from beta program or select 1.16.0.2 from the profile editor (pencil icon, next to Default) to get it.
The Google Play won't show you the stable version if you are in the beta program of the app even on Android.

**Comment by sijohans** [comment]
I realized that also, thanks! Works fine now.
