### ISSUE TITLE
libprotobuf FATAL repeated_field.h CHECK failed

### ISSUE THREAD

**Issue by hgabreu** [minecraft-linux/mcpelauncher-ui-manifest#3]
When I click "download an play", after logging in, I get the following on the logs:

```
api response body = payload {
  deliveryResponse {
    status: 3
  }
}
serverMetadata {
  latencyMillis: 44
}
serverLogsCookie: "\010\022\232\001\027\n\023\010\260\276\360\374\310\256\336\002\025d!\311\n\035\243\327\010O\020\004"

[libprotobuf FATAL /usr/include/google/protobuf/repeated_field.h:1506] CHECK failed: (index) < (current_size_): 
qml: Download failed: CHECK failed: (index) < (current_size_):
```

Any ideas?

**Comment by TheGreatMcPain** [comment]
I seem to be getting that too, but only for beta versions of the game.  Selecting the latest google play version works for me.

**Comment by MCMrARM** [comment]
For downloading beta versions you must first sign-up for the beta group. I guess a message should be shown.

**Comment by hgabreu** [comment]
Thanks, this got me thinking that maybe that were something wrong with my g play account and that was it. I had installed Minecraft as part of a "google play family" that someone else purchased. On my phone it listed normally, but I left the family group and purchased it separately, then it worked nice. Thanks
