### ISSUE TITLE
can't open the xbox window on signup

### ISSUE THREAD

**Issue by gyoo18** [minecraft-linux/mcpelauncher-ui-manifest#34]
I tried signing up in a microsoft account and I was instead greated with this :

"The Launcher might failed to open the Xboxlive login Window successfully, please report if Minecraft tells you that sign in failed. Please look into the gamelog for more Information: Process returned stdout:`ms-xal-0000000048183522://auth?status=success&log=account created&state=0JkIcLB7AAAAAAAAAAAAALAKD4rI1dV6_3gj7pOB59f-N17UDguScKlU_VfEshmbdmcZxyoZexoUrOE9F5nWOg`, but expected an url starting with:`ms-xal-0000000048183522://auth`. Try returning `ms-xal-0000000048183522://auth?status=success&log=account` as endurl. We track this issue here https://github.com/minecraft-linux/mcpelauncher-manifest/issues/444"

also, singing in while the window wasn't in fullscreen mode sloved the issue.

**Comment by ChristopherHX** [comment]
Thank you for your report, will get fixed in the next update.

> also, singing in while the window wasn't in fullscreen mode sloved the issue.

I bet, it is because you had an account on your second try.

**Comment by gyoo18** [comment]
> I bet, it is because you had an account on your second try.
