### ISSUE TITLE
Sign in with Google fails

### ISSUE THREAD

**Issue by nickgirga** [minecraft-linux/mcpelauncher-ui-manifest#39]
**Describe the bug**
Accidentally reset my mcpelauncher's UI settings, so it signed me out of my Google account. Unfortunately, when I went to sign back in, the loading icon just kept spinning and the Google sign-in page never showed up. I even left it like that for about an hour and it just kept "loading".

**To Reproduce**
1. Download the [0.3.3-683 AppImage](https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/v0.3.3-683) release
2. Run the AppImage and click "Sign in with Google"
3. Observe infinitely spinning loading icon and no information given in terminal or logs

**Expected behavior**
When you click the "Sign in with Google" button, the Google sign-in panel should pop-up in order for you to input your Google account details.

**Screenshots**
![mcpelauncher](https://user-images.githubusercontent.com/50096660/158313903-7a421040-e7a8-4236-91eb-f656b3e41ad9.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.16.13-zen1-1-zen
 - Version: v0.3.3.683-AppImage-x86_64 (build 683)
 - Installation Type: AppImage

**Additional context**
I managed to start playing again by installing and running the version on the [AUR](https://aur.archlinux.org/packages/mcpelauncher-linux-git) instead. Google kept saying it was an "insecure browser", so I just kept restarting mcpelauncher until it stopped complaining and it eventually did. Once it worked, my login credentials were saved locally again, and the AppImage version could just auto-login without ever needing to load the sign-in page.

Because the AUR version can sign-in but the AppImage version can't, it leads me to believe that this is a version-specific issue regarding cooperation with Google's sign-in system. I only recently switched to the AppImage version a few months ago and it seemed to work as expected then, so I'm not sure what has changed since then.

The game itself also functions fine. Because I still have the version/profile files, I can run my old configurations using the command line tool `mcpelauncher-client`. They function perfectly. It would seem this is just a Google issue.

**Comment by ChristopherHX** [comment]
See here for a workaroud https://github.com/minecraft-linux/mcpelauncher-manifest/issues/656#issuecomment-1032808033

**Comment by ChristopherHX** [comment]
Workaround should be applied automatically in the AppImage v0.3.4 or later
