### ISSUE TITLE
Unable to open ui-qt

### ISSUE THREAD

**Issue by vo-vg** [minecraft-linux/mcpelauncher-ui-manifest#45]
Minecraft launcher does not open because it has not been compiled to work with Qt 6.4.1.
Even after recompiling it myself, I'm still unable to open it

```
[vo@ln-10092022-1737 ~]$ mcpelauncher-ui-qt 
Cannot mix incompatible Qt library (6.4.0) with this library (6.4.1)
Abortado (`core' generado)
[vo@ln-10092022-1737 ~]$ 
```

**Comment by ChristopherHX** [comment]
Uninstall Qt 6.4.0, then recompile.

_This sounds like an incomplete archlinux upgrade, don't forget AUR qt packages_. Nothing in this repository references exact qt versions.

I never got such an error by using ubuntu instead of a rolling distro.

**Comment by vo-vg** [comment]
recompiled both this package and qt6gtk2 (which I think it was the actual issue). Now it works
