### ISSUE TITLE
Cannot change data directory on flatpak version

### ISSUE THREAD

**Issue by GameParrot** [minecraft-linux/mcpelauncher-ui-manifest#49]
**Describe the bug**
On the Flatpak version of the Launcher, it is impossible to change the data directory. When you click the three dots to change it and select a folder, the path does not change. If you type in a path manually, the new path is there but the game still uses the default directory.

**To Reproduce**
1. Go to Edit
2. Click on Data Directory
3. Select a new folder
4. See that the path does not change

**Expected behavior**
The path should change and be obeyed by the game

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1
 - Version v0.8.0-flatpak-qt6 (build 55)
 - Installation Type flatpak
 
**Additional context**
The Appimage version does not have this issue.

**Comment by ChristopherHX** [comment]
Fixed in [d27da18ca159b1e962f0c47b25827db5f3f5bd0c](https://github.com/minecraft-linux/mcpelauncher-ui-manifest/commit/d27da18ca159b1e962f0c47b25827db5f3f5bd0c)
