### ISSUE TITLE
Download failed while downloading Minecraft 1.93.73.02 from google play.

### ISSUE THREAD

**Issue by GyanPrakash2483** [minecraft-linux/mcpelauncher-ui-manifest#51]
**Describe the bug**
Download Failed:
Error while extracting the downloaded file(s), [please report this error](https://github.com/minecraft-linux/mcpelauncher-ui-manifest/issues): The specified files are not a valid collection of Minecraft apks, they don't contain libminecraftpe.so
Valid Minecraft apk CPU architectures for this pc / launcher are x86_64, x86

**To Reproduce**
1. Go to 'minecraft bedrock launcher'
2. Click on 'DOWNLOAD AND PLAY MINECRAFT 1.19.73.02'
3. Wait for download to finish

**Expected behavior**
Minecraft should be successfully downloaded and installed.

**Screenshots**
![Screenshot from 2023-03-31 07-09-44](https://user-images.githubusercontent.com/69905535/229001272-c45e2a06-47ed-4acc-a9e6-e3f199517a35.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Version: Pulled from github on 28th March
 - Installation Type: Built from source

**Additional context**
- It worked as expected for past two versions of minecraft.
- It was built using the same commands as in documentation without any changes.

**Comment by ChristopherHX** [comment]
Please check that you have at least 3GB of free storage on the drive containing ~/.local/share/mcpelauncher.

There are no new known issues with the downloader, however it sometimes fails.

**Comment by GyanPrakash2483** [comment]
I have 207GB free storage on that drive

**Comment by GyanPrakash2483** [comment]
nvm, it is fixed after a few days
