### ISSUE TITLE
Refuses to launch because of misspelled protobuf version?

### ISSUE THREAD

**Issue by figuld** [minecraft-linux/mcpelauncher-ui-manifest#57]
**Describe the bug**
Requires `libprotobuf.so.32` while [the actual version is 23](https://github.com/protocolbuffers/protobuf/tags).

**To Reproduce**
1. Launch `mcpelauncher-ui-qt` for the terminal.
2. See the error.

**Expected behavior**
The launcher should require version 23 instead?

**Screenshots**
```
[remorin@chuwawa:0 ~]$ mcpelauncher-ui-qt
mcpelauncher-ui-qt: error while loading shared libraries: libprotobuf.so.32: cannot open shared object file: No such file or directory
[ble: exit 127]
```

**Desktop (please complete the following information):**
 - OS: [Arch Linux]
 - Version [v0.9.0.qt6.r1.ge52a436-1]
 - Installation Type [chaotic-aur]

**Additional context**
None.

**Comment by ChristopherHX** [comment]
See https://bbs.archlinux.org/viewtopic.php?id=287189

> The launcher should require version 23 instead?

The launcher doesn't require any specfic protobuf version.

By building the launcher your system decides what suffix libprotobuf has.

You did a pacman update, which removed a `.so` file and you haven't installed an updated build of the aur package.

Archlinux is something for real linux experts, who expect that AUR software breaks on updates and you need to rebuild all AUR packages.

Chaotic AUR seems to be an easy / fast way to use this launcher on arch, but not perfect.

**Comment by figuld** [comment]
Got fixed, closing.
