### ISSUE TITLE
Error while extracting the downloaded file(s), please report this error: Failed to open output file

### ISSUE THREAD

**Issue by emperortrademark999** [minecraft-linux/mcpelauncher-ui-manifest#61]
**Describe the bug**
when installing any version, such as 1.20.30 or 1.20.15, it will give an error saying "Error while extracting the downloaded file(s), [please report this error]: Failed to open output file"

**To Reproduce**
1. Go to the app
2. Click on 1.20.15 or any version above 1.20 in the version selector
3. Press download and play button

**Expected behavior**
I expected for it to launch normally, but during extraction process it had an error.

**Desktop (please complete the following information):**
 - OS: Linux - Ubuntu
 - Version: v0.11.0-qt6
 - Installation Type: AppImage

**Additional context**
This only happened when updating the launcher from the previous version.

**Comment by peppefailla** [comment]
Same error! Waiting for a response

**Comment by ChristopherHX** [comment]
You need more disk space, the game is nowadays between 1-2GB installed + the need of the downloaded archives

**Comment by emperortrademark999** [comment]
> You need more disk space, the game is nowadays between 1-2GB installed + the need of the downloaded archives

Forgot I had this issue open, only noticed once I got an e-mail about it. I fixed it by freeing up my storage, since at the time I had about 2-3 GB left on the PC I was using to run the launcher.

**Comment by peppefailla** [comment]
> You need more disk space, the game is nowadays between 1-2GB installed + the need of the downloaded archives

I've got about 33gb of storage left so I dont think that's the issue
![image](https://github.com/user-attachments/assets/83283bc8-12fa-4007-8091-84ef16dd949f)

EDIT: I installed the AppImage build and it seems to be working fine. I think that might be an issue of flatpak or smth.
Thanks for the assistance though!
