### ISSUE TITLE
Failed to open output file

### ISSUE THREAD

**Issue by FrostyNick** [minecraft-linux/mcpelauncher-ui-manifest#65]
**Describe the bug**

**To Reproduce**
1. Installed this AppImage from [am](https://github.com/ivan-hc/AM) and it was outdated and it let me update the AppImage inside the launcher.. I'd assume the newest stable version now?
2. Login to Minecraft, prompts me to create a local password, I do that.
3. "DOWNLOAD AND PLAY". It downloads Minecraft and then:

**Expected behavior**
Doesn't have error. If it does error, having more verbose logs of what is happening might also help.

**Screenshots**
![2024-06-17T13:43:07,100557036-05:00](https://github.com/minecraft-linux/mcpelauncher-ui-manifest/assets/57016218/853e0c60-231a-4414-90cd-451668f96140)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version v0.15.0.369-AppImage-x86_64 (build 369)]
 - Installation Type: AppImage

**Additional context**

**Comment by ChristopherHX** [comment]
The Game is currently between 1GiB - 2GiB big (it was much less a few years ago), if you have some older versions of the game then you might want to delete them.
It needs to be able to both download the archive and extract it, the game might be even larger extracted

You probably have no 10GiB+ free disk space where the launcher downloads and extract the game

**Comment by ChristopherHX** [comment]
Even my phone refuses to update Minecraft and tells me to uninstall apps, since my phone's diskspace is near the limit

**Comment by FrostyNick** [comment]
Yeah, I needed more free space. I guess I didn't expect it to take 2.5 GB to install this, which is completely reasonable. Minecraft PE was indeed way smaller some years back on mobile.. Thanks for help.
