### ISSUE TITLE
Make it so that clicking enter after typing password opens the launcher instead of using mouse to click the continue button

### ISSUE THREAD

**Issue by ghost** [minecraft-linux/mcpelauncher-ui-manifest#68]
**Describe the solution you'd like**
When a user presses the enter button after entering the password, the login should happen. Currently the only way is to use mouse to move over to the button and click it. It is a little bit slower and inconvenient as it is opposite of how most form like GUIs work.

**Additional context**
![image](https://github.com/user-attachments/assets/fe7d269b-f1fa-4868-9edc-0eb07e40e56e)

**Comment by ChristopherHX** [comment]
I believe this feature is pending in nighly builds to be released later

**Comment by ghost** [comment]
op sorry, did not know that.
