### ISSUE TITLE
add menu to change the apk

### ISSUE THREAD

**Issue by abasgames** [minecraft-linux/mcpelauncher-ui-manifest#7]
add menu to change the apk 
i get minecraft 1.2.10 apk for test and work so i want to 1.7.13 but i dont found any way to uninstall 1.2.10 any fix ?

**Comment by MCMrARM** [comment]
Has been implemented by https://github.com/minecraft-linux/mcpelauncher-ui-qt/commit/feda212b020244b29ba98d8c7198c77432b20b9e
